version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
